const games=[
{id:'platformer',name:'Super Jump',cat:'arcade',icon:'🦘',desc:'Plataforma infinita: pule, desvie e faça pontos.'},
{id:'snake',name:'Snake',cat:'classic',icon:'🐍',desc:'Colete a comida e aumente sua pontuação.'},
{id:'blocks',name:'Block Master',cat:'classic',icon:'🧱',desc:'Empilhe blocos e mantenha a torre de pé.'},
{id:'racer',name:'Neon Racer',cat:'arcade',icon:'🏎️',desc:'Desvie do trânsito e sobreviva o máximo possível.'},
{id:'memory',name:'Memory Cards',cat:'classic',icon:'🃏',desc:'Encontre os pares no menor número de tentativas.'},
{id:'clicker',name:'Coin Clicker',cat:'arcade',icon:'🪙',desc:'Clique, compre melhorias e aumente sua produção.'},
{id:'car',name:'Simulador de Carro',cat:'sim',icon:'🚗',desc:'Aceleração, velocidade, combustível e consumo.'},
{id:'flight',name:'Simulador de Voo',cat:'sim',icon:'✈️',desc:'Controle altitude, velocidade e combustível.'}
];
const grid=document.querySelector('#grid'), modal=document.querySelector('#modal'), area=document.querySelector('#gameArea');
function render(filter='all',q=''){grid.innerHTML=games.filter(g=>(filter==='all'||g.cat===filter)&&g.name.toLowerCase().includes(q.toLowerCase())).map(g=>`<article class="card" data-launch="${g.id}"><div class="thumb">${g.icon}</div><h3>${g.name}</h3><p>${g.desc}</p><div class="tag">${g.cat.toUpperCase()} • JOGAR</div></article>`).join('');document.querySelectorAll('[data-launch]').forEach(b=>b.onclick=()=>launch(b.dataset.launch))}
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.navbtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter,document.querySelector('#search').value)});
document.querySelector('#search').oninput=e=>render(document.querySelector('.navbtn.active').dataset.filter,e.target.value);
document.querySelector('#close').onclick=()=>{modal.classList.add('hidden');area.innerHTML=''};
modal.onclick=e=>{if(e.target===modal){modal.classList.add('hidden');area.innerHTML=''}};
function launch(id){const g=games.find(x=>x.id===id);document.querySelector('#gameCategory').textContent=g.cat.toUpperCase();document.querySelector('#gameTitle').textContent=g.name;modal.classList.remove('hidden');if(id==='platformer')platformer();else if(id==='snake')snake();else if(id==='blocks')blocks();else if(id==='racer')racer();else if(id==='memory')memory();else if(id==='clicker')clicker();else if(id==='car')simCar();else if(id==='flight')simFlight()}
function canvasGame(h=420){area.innerHTML='<div class="game-wrap"><canvas id="game" width="760" height="'+h+'"></canvas><div id="score" class="score"></div><div class="controls">Use teclado • Espaço / setas • No celular, toque na tela</div></div>';return [document.querySelector('#game'),document.querySelector('#score')]}
function platformer(){const[c,s]=canvasGame(400),x=c.getContext('2d');let p={x:80,y:300,vx:0,vy:0},obs=[],score=0,over=false,keys={};addEventListener('keydown',e=>keys[e.key]=1);addEventListener('keyup',e=>keys[e.key]=0);for(let i=0;i<8;i++)obs.push({x:220+i*110,y:330-Math.random()*120,w:80,h:18});function loop(){x.clearRect(0,0,c.width,c.height);x.fillStyle='#101b30';x.fillRect(0,0,c.width,c.height);x.fillStyle='#18d6a0';x.fillRect(0,350,c.width,50);x.fillStyle='#6d5dfc';x.fillRect(p.x,p.y,28,36);if(keys.ArrowLeft)p.vx=-4;if(keys.ArrowRight)p.vx=4;if(!keys.ArrowLeft&&!keys.ArrowRight)p.vx*=.8;if((keys[' ']||keys.ArrowUp)&&p.y>=314)p.vy=-10;p.vy+=.5;p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=0;if(p.x>730)p.x=730;if(p.y>314){p.y=314;p.vy=0}obs.forEach(o=>{o.x-=2;if(o.x<-90){o.x=800;score++;o.y=260-Math.random()*100}x.fillStyle='#f59e0b';x.fillRect(o.x,o.y,o.w,o.h);if(p.x<o.x+o.w&&p.x+28>o.x&&p.y+36>o.y&&p.y<o.y+o.h)over=true});s.textContent=over?'💥 Fim de jogo — feche e tente novamente':'Pontos: '+score;if(!over)requestAnimationFrame(loop)}loop()}
function snake(){const[c,s]=canvasGame(420),x=c.getContext('2d'),N=21,sz=20;let a=[{x:10,y:10}],d={x:1,y:0},food={x:5,y:5},over=false,sc=0;function key(e){if(e.key==='ArrowUp'&&d.y===0)d={x:0,y:-1};if(e.key==='ArrowDown'&&d.y===0)d={x:0,y:1};if(e.key==='ArrowLeft'&&d.x===0)d={x:-1,y:0};if(e.key==='ArrowRight'&&d.x===0)d={x:1,y:0}}addEventListener('keydown',key);function loop(){let h={x:a[0].x+d.x,y:a[0].y+d.y};if(h.x<0||h.y<0||h.x>=N||h.y>=N||a.some(q=>q.x===h.x&&q.y===h.y))over=true;a.unshift(h);if(h.x===food.x&&h.y===food.y){sc++;food={x:Math.floor(Math.random()*N),y:Math.floor(Math.random()*N)}}else a.pop();x.fillStyle='#08101b';x.fillRect(0,0,c.width,c.height);x.fillStyle='#18d6a0';a.forEach(q=>x.fillRect(q.x*sz,q.y*sz,sz-2,sz-2));x.fillStyle='#ff4d6d';x.fillRect(food.x*sz,food.y*sz,sz-2,sz-2);s.textContent=over?'💥 Fim de jogo':'Pontos: '+sc;if(!over)setTimeout(()=>requestAnimationFrame(loop),105)}loop()}
function blocks(){const[c,s]=canvasGame(420),x=c.getContext('2d');let y=380,h=18,w=120,dir=1,stack=0;function loop(){x.clearRect(0,0,c.width,c.height);x.fillStyle='#080e19';x.fillRect(0,0,c.width,c.height);x.fillStyle='#18d6a0';x.fillRect(0,398,c.width,22);x.fillStyle='#6d5dfc';let px=((Date.now()/3)% (760-w*2));if(Math.floor(Date.now()/1000)%2)px=760-w*2-px;x.fillRect(px,y,w,h);x.fillStyle='#fff';x.fillText('Clique para soltar o bloco',280,30);s.textContent='Altura: '+stack;requestAnimationFrame(loop)}loop();c.onclick=()=>{stack++;y=Math.max(80,y-18)}}
function racer(){const[c,s]=canvasGame(420),x=c.getContext('2d');let car=350,obs=[],score=0,keys={};addEventListener('keydown',e=>keys[e.key]=1);addEventListener('keyup',e=>keys[e.key]=0);for(let i=0;i<5;i++)obs.push({x:150+Math.random()*500,y:-i*120});function loop(){x.fillStyle='#101010';x.fillRect(0,0,c.width,c.height);x.fillStyle='#333';x.fillRect(170,0,420,c.height);x.strokeStyle='#fff';x.setLineDash([30,30]);x.lineDashOffset=-Date.now()/5;x.beginPath();x.moveTo(380,0);x.lineTo(380,c.height);x.stroke();x.setLineDash([]);if(keys.ArrowLeft)car-=6;if(keys.ArrowRight)car+=6;car=Math.max(180,Math.min(550,car));x.fillStyle='#18d6a0';x.fillRect(car,330,42,65);obs.forEach(o=>{o.y+=5;if(o.y>430){o.y=-80;o.x=190+Math.random()*360;score++}x.fillStyle='#ff4d6d';x.fillRect(o.x,o.y,42,65);if(car<o.x+42&&car+42>o.x&&330<o.y+65&&395>o.y)s.textContent='💥 Bateu! Pontos: '+score});if(!s.textContent.startsWith('💥')){s.textContent='Pontos: '+score;requestAnimationFrame(loop)}}loop()}
function memory(){area.innerHTML='<div class="game-wrap"><div id="mem" class="grid"></div><div id="score" class="score">Tentativas: 0</div></div>';let vals=['🍎','🚀','🎮','⚽','🐱','⭐','🍕','🎯'];let deck=[...vals,...vals].sort(()=>Math.random()-.5),first=null,lock=false,tries=0,found=0,m=document.querySelector('#mem'),sc=document.querySelector('#score');m.style.gridTemplateColumns='repeat(4,1fr)';deck.forEach((v,i)=>{let b=document.createElement('button');b.style.cssText='height:80px;font-size:30px;background:#151f31;border:1px solid #253149;border-radius:10px;color:white;cursor:pointer';b.textContent='?';b.onclick=()=>{if(lock||b.dataset.done)return;b.textContent=v;if(!first){first={b,v}}else{tries++;if(first.v===v){first.b.dataset.done=b.dataset.done=1;found+=2;first=null}else{lock=true;let f=first;first=null;setTimeout(()=>{f.b.textContent=b.textContent='?';lock=false},500)}}sc.textContent=found===16?'🏆 Concluído! Tentativas: '+tries:'Tentativas: '+tries};m.appendChild(b)})}
function clicker(){area.innerHTML='<div class="game-wrap"><div style="font-size:90px;cursor:pointer" id="coin">🪙</div><div id="coins" class="score">0 moedas</div><button class="primary" id="upgrade">Melhoria: 10 moedas</button></div>';let n=0,p=1,coin=document.querySelector('#coin'),out=document.querySelector('#coins'),up=document.querySelector('#upgrade');coin.onclick=()=>{n+=p;out.textContent=n+' moedas • +'+p+'/clique'};up.onclick=()=>{if(n>=10){n-=10;p++;up.textContent='Melhoria: '+(10*p)+' moedas';out.textContent=n+' moedas • +'+p+'/clique'}}}
function simCar(){area.innerHTML='<div class="sim-panel"><div class="box"><h3>🚗 Painel</h3><p>Velocidade: <b id="v">0</b> km/h</p><p>RPM: <b id="rpm">800</b></p><p>Combustível: <b id="fuel">100</b>%</p><input id="th" type="range" min="0" max="100" value="0"><button id="reset">Resetar</button></div><div class="box"><h3>Simulação</h3><p>Use o acelerador para aumentar a velocidade. O consumo cresce com a carga.</p><div id="road" style="height:180px;border-radius:12px;background:repeating-linear-gradient(90deg,#222 0 80px,#333 80px 160px);display:grid;place-items:center;font-size:55px">🚗</div></div></div>';let v=0,f=100;setInterval(()=>{let t=+document.querySelector('#th').value;v+=(t-v/2)*.02;f=Math.max(0,f-t*.0008);document.querySelector('#v').textContent=v.toFixed(0);document.querySelector('#rpm').textContent=Math.round(800+v*55);document.querySelector('#fuel').textContent=f.toFixed(1)},100);document.querySelector('#reset').onclick=()=>{v=0;f=100}}
function simFlight(){area.innerHTML='<div class="sim-panel"><div class="box"><h3>✈️ Instrumentos</h3><p>Altitude: <b id="alt">3000</b> ft</p><p>Velocidade: <b id="spd">180</b> kt</p><p>Combustível: <b id="ff">100</b>%</p><input id="power" type="range" min="0" max="100" value="55"><input id="pitch" type="range" min="-20" max="20" value="0"><button id="level">Nivelar</button></div><div class="box"><h3>Controles</h3><p>Potência controla velocidade. Pitch positivo sobe; negativo desce.</p><div style="font-size:100px;text-align:center;padding:25px">✈️</div></div></div>';let alt=3000,spd=180,f=100;setInterval(()=>{let power=+document.querySelector('#power').value,pitch=+document.querySelector('#pitch').value;spd+=(power-55)*.08;alt+=pitch*.8;f=Math.max(0,f*.999);document.querySelector('#alt').textContent=Math.round(alt);document.querySelector('#spd').textContent=Math.round(spd);document.querySelector('#ff').textContent=f.toFixed(1)},100);document.querySelector('#level').onclick=()=>document.querySelector('#pitch').value=0}
render();